# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_method_override: true
    trusted_proxies: ~

    session:
        cookie_secure: auto
        cookie_samesite: strict

    csrf_protection: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
